# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Конец'),
        ),
    ]
