# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170731_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=64, verbose_name='Учебное заведение')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('department', models.CharField(blank=True, max_length=32, verbose_name='Факультет')),
                ('speciality', models.CharField(max_length=64, verbose_name='Специальность')),
                ('start', models.DateField(verbose_name='Начало')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='Конец')),
            ],
        ),
    ]
