# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('region', models.CharField(max_length=32, verbose_name='Регион')),
                ('tax_id', models.IntegerField(verbose_name='ИНН')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='region',
        ),
        migrations.RemoveField(
            model_name='work',
            name='site',
        ),
    ]
