# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170803_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Организация'),
        ),
    ]
