# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170803_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
